{
 "title": "TuIndependiente",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Visits main page",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_main", "legendFormat": "Visit main page" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_total", "legendFormat": "Total requests" },
    { "expr": "myapp_requests_fails", "legendFormat": "Bad requests" }
   ]
  },
  {
   "title": "Requests to cancel service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_cancel", "legendFormat": "requests to cancel a service" }
   ]
  },
  {
   "title": "Application health",
   "type": "stat",
   "description": "Application health",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_health", "legendFormat": "application health" }
   ]
  },
  {
   "title": "Requests to create service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_add", "legendFormat": "Requests to /add" }
   ]
  },
  {
   "title": "Programming language",
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "options": {
    "content": "# Golang Version\n\n  go 1.20.5\n           "
   },
   "targets": [
    { "expr": "myapp_requests_mul", "legendFormat": "requests to /mul" }
   ]
  },
  {
   "title": "In use | total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "App version",
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "options": {
    "content": "# TuIndependiente\n  v1.0.0 \\\\\n  You can find the API: [TuIndependiente](http://staging-lb-1383736276.us-east-1.elb.amazonaws.com/docs/)\n           "
   },
   "targets": [
    { "expr": "myapp_requests_div", "legendFormat": "requests to /div" }
   ]
  }
 ]
}