definitions:
  main.GreeterResponse:
    properties:
      message:
        type: string
    type: object
  main.ServiceResponse:
    properties:
      result:
        type: string
    type: object
info:
  contact: {}
paths:
  /greeter:
    get:
      operationId: "1"
      parameters:
      - description: Input name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.GreeterResponse'
      summary: Greeter service
  /health:
    get:
      operationId: "7"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.GreeterResponse'
      summary: Health service
  /service/cancel:
    delete:
      operationId: "4"
      parameters:
      - description: serviceID
        in: formData
        name: serviceID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ServiceResponse'
      summary: Cancel service
  /service/create:
    post:
      operationId: "2"
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: address
        in: formData
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ServiceResponse'
      summary: Create service
swagger: "2.0"
